name: NPM PUBLISH
on:
  push:
    branches:
      - master
jobs:
  build:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install 
        run: npm install
      - name: Build
        run: npm run build:prod
      - name: Publish
        working-directory: ./dist/ng10-rut
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}